# Site settings
title: Pan-American Taikai

email: info@pan-american-taikai.com

description: > # this means to ignore newlines until "baseurl:"
  Official website for the Pan-American Taikai
  
baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://locahost:4000" # the base hostname & protocol for your site

twitter_username: 

github_username:  

# Build settings
markdown: kramdown

event_name: Pan-American Taikai
date: July 27-28, 2019
city_state_location: Long Beach, California, USA
